# Generated by Django 3.2.8 on 2021-10-22 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='fecha',
        ),
    ]
