# Generated by Django 3.2.8 on 2021-10-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_remove_partido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
